O_FILES := $(BUILD_DIR)/asm/code/__start.c.o \
$(BUILD_DIR)/asm/code/__ppc_eabi_init.cpp.o \
$(BUILD_DIR)/asm/code/__mem.c.o \
$(BUILD_DIR)/asm/code/mem/TRK.c.o \
$(BUILD_DIR)/asm/code/__exception.s.o \
$(BUILD_DIR)/asm/code/dolphin/trk.c.o \
$(BUILD_DIR)/asm/code/THPAudio.c.o \
$(BUILD_DIR)/asm/extab.o \
$(BUILD_DIR)/asm/extabindex.o \
$(BUILD_DIR)/asm/code/syncaudio.cpp.o \
$(BUILD_DIR)/asm/code/objectdatafactory.cpp.o \
$(BUILD_DIR)/asm/code/game/animation/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/cas/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/interactor/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/level/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/misc/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/simulator/core2/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/simulator/core/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/simulator/objectdata/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/simulator/utility/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/statemachine/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/ui/core/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/ui/targets/cas/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/ui/targets/s2c/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/ui/targets/tsc5/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/ui/targets/tsc6/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/unity.cpp.o \
$(BUILD_DIR)/asm/code/game/wii/unity.cpp.o \
$(BUILD_DIR)/asm/code/weather/unity.cpp.o \
$(BUILD_DIR)/asm/code/base/core/engine/dependencies/unity.cpp.o \
$(BUILD_DIR)/asm/code/base/core/unity.cpp.o \
$(BUILD_DIR)/asm/code/base/ngc/unity.cpp.o \
$(BUILD_DIR)/asm/code/e/cheatmenu.cpp.o \
$(BUILD_DIR)/asm/code/engine/core/unity.cpp.o \
$(BUILD_DIR)/asm/code/engine/effects2/unity.cpp.o \
$(BUILD_DIR)/asm/code/engine/effects/unity.cpp.o \
$(BUILD_DIR)/asm/code/engine/graphics/unity.cpp.o \
$(BUILD_DIR)/asm/code/engine/manager/unity.cpp.o \
$(BUILD_DIR)/asm/code/engine/ngc/unity.cpp.o \
$(BUILD_DIR)/asm/code/engine/resource/unity.cpp.o \
$(BUILD_DIR)/asm/code/engine/utility/unity.cpp.o \
$(BUILD_DIR)/asm/code/fixed/pool.cpp.o \
$(BUILD_DIR)/asm/code/hashtable.cpp.o \
$(BUILD_DIR)/asm/code/red/black/tree.cpp.o \
$(BUILD_DIR)/asm/code/Apt.cpp.o \
$(BUILD_DIR)/asm/code/AptActionInterpreter.cpp.o \
$(BUILD_DIR)/asm/code/AptAnimation.cpp.o \
$(BUILD_DIR)/asm/code/AptArray.cpp.o \
$(BUILD_DIR)/asm/code/AptCharacter.cpp.o \
$(BUILD_DIR)/asm/code/AptCharacterInstButton.cpp.o \
$(BUILD_DIR)/asm/code/AptCIH.cpp.o \
$(BUILD_DIR)/asm/code/AptDate.cpp.o \
$(BUILD_DIR)/asm/code/AptDisplayList.cpp.o \
$(BUILD_DIR)/asm/code/AptGC.cpp.o \
$(BUILD_DIR)/asm/code/AptInput.cpp.o \
$(BUILD_DIR)/asm/code/AptLoad.cpp.o \
$(BUILD_DIR)/asm/code/AptMath.cpp.o \
$(BUILD_DIR)/asm/code/AptMiscObjects.cpp.o \
$(BUILD_DIR)/asm/code/AptMovie.cpp.o \
$(BUILD_DIR)/asm/code/AptNativeHash.cpp.o \
$(BUILD_DIR)/asm/code/AptRand.cpp.o \
$(BUILD_DIR)/asm/code/AptRenderingContext.cpp.o \
$(BUILD_DIR)/asm/code/AptSound.cpp.o \
$(BUILD_DIR)/asm/code/AptSpriteMembers.cpp.o \
$(BUILD_DIR)/asm/code/AptStageMembers.cpp.o \
$(BUILD_DIR)/asm/code/AptString.cpp.o \
$(BUILD_DIR)/asm/code/AptTextFormat.cpp.o \
$(BUILD_DIR)/asm/code/AptValue.cpp.o \
$(BUILD_DIR)/asm/code/AptValueFactory.cpp.o \
$(BUILD_DIR)/asm/code/AptValueGCAllocator.cpp.o \
$(BUILD_DIR)/asm/code/AptXmlMembers.cpp.o \
$(BUILD_DIR)/asm/code/DogmaAllocator.cpp.o \
$(BUILD_DIR)/asm/code/AptGlobalObject.cpp.o \
$(BUILD_DIR)/asm/code/AptObject.cpp.o \
$(BUILD_DIR)/asm/code/AptScriptColour.cpp.o \
$(BUILD_DIR)/asm/code/AptScriptFunction.cpp.o \
$(BUILD_DIR)/asm/code/AptXml.cpp.o \
$(BUILD_DIR)/asm/code/AptXmlAttributes.cpp.o \
$(BUILD_DIR)/asm/code/AptXmlNode.cpp.o \
$(BUILD_DIR)/asm/code/AptBoolean.cpp.o \
$(BUILD_DIR)/asm/code/AptFloat.cpp.o \
$(BUILD_DIR)/asm/code/AptInteger.cpp.o \
$(BUILD_DIR)/asm/code/AptValueVector.cpp.o \
$(BUILD_DIR)/asm/code/EAString.cpp.o \
$(BUILD_DIR)/asm/code/StringPool.cpp.o \
$(BUILD_DIR)/asm/code/ai.c.o \
$(BUILD_DIR)/asm/code/arc.c.o \
$(BUILD_DIR)/asm/code/AX.c.o \
$(BUILD_DIR)/asm/code/AXAlloc.c.o \
$(BUILD_DIR)/asm/code/AXAux.c.o \
$(BUILD_DIR)/asm/code/AXCL.c.o \
$(BUILD_DIR)/asm/code/AXOut.c.o \
$(BUILD_DIR)/asm/code/AXSPB.c.o \
$(BUILD_DIR)/asm/code/AXVPB.c.o \
$(BUILD_DIR)/asm/code/AXProf.c.o \
$(BUILD_DIR)/asm/code/AXFXReverbHi.c.o \
$(BUILD_DIR)/asm/code/AXFXReverbHiExp.c.o \
$(BUILD_DIR)/asm/code/AXFXHooks.c.o \
$(BUILD_DIR)/asm/code/PPCArch.c.o \
$(BUILD_DIR)/asm/code/gki/buffer.c.o \
$(BUILD_DIR)/asm/code/gki/time.c.o \
$(BUILD_DIR)/asm/code/gki/ppc.c.o \
$(BUILD_DIR)/asm/code/hcisu/h2.c.o \
$(BUILD_DIR)/asm/code/uusb/ppc.c.o \
$(BUILD_DIR)/asm/code/bte/hcisu.c.o \
$(BUILD_DIR)/asm/code/bte/init.c.o \
$(BUILD_DIR)/asm/code/bte/logmsg.c.o \
$(BUILD_DIR)/asm/code/bte/main.c.o \
$(BUILD_DIR)/asm/code/btu/task1.c.o \
$(BUILD_DIR)/asm/code/bd.c.o \
$(BUILD_DIR)/asm/code/bta/sys/conn.c.o \
$(BUILD_DIR)/asm/code/bta/sys/main.c.o \
$(BUILD_DIR)/asm/code/ptim.c.o \
$(BUILD_DIR)/asm/code/utl.c.o \
$(BUILD_DIR)/asm/code/bta/dm/act.c.o \
$(BUILD_DIR)/asm/code/bta/dm/api.c.o \
$(BUILD_DIR)/asm/code/bta/dm/main.c.o \
$(BUILD_DIR)/asm/code/bta/dm/pm.c.o \
$(BUILD_DIR)/asm/code/bta/hh/act.c.o \
$(BUILD_DIR)/asm/code/bta/hh/api.c.o \
$(BUILD_DIR)/asm/code/bta/hh/main.c.o \
$(BUILD_DIR)/asm/code/bta/hh/utils.c.o \
$(BUILD_DIR)/asm/code/btm/acl.c.o \
$(BUILD_DIR)/asm/code/btm/dev.c.o \
$(BUILD_DIR)/asm/code/btm/devctl.c.o \
$(BUILD_DIR)/asm/code/btm/discovery.c.o \
$(BUILD_DIR)/asm/code/btm/inq.c.o \
$(BUILD_DIR)/asm/code/btm/main.c.o \
$(BUILD_DIR)/asm/code/btm/pm.c.o \
$(BUILD_DIR)/asm/code/btm/sco.c.o \
$(BUILD_DIR)/asm/code/btm/sec.c.o \
$(BUILD_DIR)/asm/code/btu/hcif.c.o \
$(BUILD_DIR)/asm/code/btu/init.c.o \
$(BUILD_DIR)/asm/code/wbt/ext.c.o \
$(BUILD_DIR)/asm/code/gap/api.c.o \
$(BUILD_DIR)/asm/code/gap/conn.c.o \
$(BUILD_DIR)/asm/code/gap/utils.c.o \
$(BUILD_DIR)/asm/code/hcicmds.c.o \
$(BUILD_DIR)/asm/code/hidd/api.c.o \
$(BUILD_DIR)/asm/code/hidd/conn.c.o \
$(BUILD_DIR)/asm/code/hidd/mgmt.c.o \
$(BUILD_DIR)/asm/code/hidd/pm.c.o \
$(BUILD_DIR)/asm/code/hidh/api.c.o \
$(BUILD_DIR)/asm/code/hidh/conn.c.o \
$(BUILD_DIR)/asm/code/l2c/api.c.o \
$(BUILD_DIR)/asm/code/l2c/csm.c.o \
$(BUILD_DIR)/asm/code/l2c/link.c.o \
$(BUILD_DIR)/asm/code/l2c/main.c.o \
$(BUILD_DIR)/asm/code/l2c/utils.c.o \
$(BUILD_DIR)/asm/code/port/api.c.o \
$(BUILD_DIR)/asm/code/port/rfc.c.o \
$(BUILD_DIR)/asm/code/port/utils.c.o \
$(BUILD_DIR)/asm/code/rfc/l2cap/if.c.o \
$(BUILD_DIR)/asm/code/rfc/mx/fsm.c.o \
$(BUILD_DIR)/asm/code/rfc/port/fsm.c.o \
$(BUILD_DIR)/asm/code/rfc/port/if.c.o \
$(BUILD_DIR)/asm/code/rfc/ts/frames.c.o \
$(BUILD_DIR)/asm/code/rfc/utils.c.o \
$(BUILD_DIR)/asm/code/sdp/api.c.o \
$(BUILD_DIR)/asm/code/sdp/db.c.o \
$(BUILD_DIR)/asm/code/sdp/discovery.c.o \
$(BUILD_DIR)/asm/code/sdp/main.c.o \
$(BUILD_DIR)/asm/code/sdp/server.c.o \
$(BUILD_DIR)/asm/code/sdp/utils.c.o \
$(BUILD_DIR)/asm/code/db.c.o \
$(BUILD_DIR)/asm/code/dsp.c.o \
$(BUILD_DIR)/asm/code/dsp/debug.c.o \
$(BUILD_DIR)/asm/code/dsp/task.c.o \
$(BUILD_DIR)/asm/code/dvdfs.c.o \
$(BUILD_DIR)/asm/code/dvd.c.o \
$(BUILD_DIR)/asm/code/dvdqueue.c.o \
$(BUILD_DIR)/asm/code/dvderror.c.o \
$(BUILD_DIR)/asm/code/dvdidutils.c.o \
$(BUILD_DIR)/asm/code/dvdFatal.c.o \
$(BUILD_DIR)/asm/code/dvd/broadway.c.o \
$(BUILD_DIR)/asm/code/euart.c.o \
$(BUILD_DIR)/asm/code/EXIBios.c.o \
$(BUILD_DIR)/asm/code/EXIUart.c.o \
$(BUILD_DIR)/asm/code/EXICommon.c.o \
$(BUILD_DIR)/asm/code/fs.c.o \
$(BUILD_DIR)/asm/code/GXInit.c.o \
$(BUILD_DIR)/asm/code/GXFifo.c.o \
$(BUILD_DIR)/asm/code/GXAttr.c.o \
$(BUILD_DIR)/asm/code/GXMisc.c.o \
$(BUILD_DIR)/asm/code/GXGeometry.c.o \
$(BUILD_DIR)/asm/code/GXFrameBuf.c.o \
$(BUILD_DIR)/asm/code/GXLight.c.o \
$(BUILD_DIR)/asm/code/GXTexture.c.o \
$(BUILD_DIR)/asm/code/GXBump.c.o \
$(BUILD_DIR)/asm/code/GXTev.c.o \
$(BUILD_DIR)/asm/code/GXPixel.c.o \
$(BUILD_DIR)/asm/code/GXDisplayList.c.o \
$(BUILD_DIR)/asm/code/GXTransform.c.o \
$(BUILD_DIR)/asm/code/GXPerf.c.o \
$(BUILD_DIR)/asm/code/HBMAnmController.cpp.o \
$(BUILD_DIR)/asm/code/HBMBase.cpp.o \
$(BUILD_DIR)/asm/code/HBMController.cpp.o \
$(BUILD_DIR)/asm/code/HBMFrameController.cpp.o \
$(BUILD_DIR)/asm/code/HBMGUIManager.cpp.o \
$(BUILD_DIR)/asm/code/HBMRemoteSpk.cpp.o \
$(BUILD_DIR)/asm/code/db/assert.cpp.o \
$(BUILD_DIR)/asm/code/db/console.cpp.o \
$(BUILD_DIR)/asm/code/db/DbgPrintBase.cpp.o \
$(BUILD_DIR)/asm/code/db/directPrint.cpp.o \
$(BUILD_DIR)/asm/code/db/mapFile.cpp.o \
$(BUILD_DIR)/asm/code/lyt/animation.cpp.o \
$(BUILD_DIR)/asm/code/lyt/arcResourceAccessor.cpp.o \
$(BUILD_DIR)/asm/code/lyt/bounding.cpp.o \
$(BUILD_DIR)/asm/code/lyt/common.cpp.o \
$(BUILD_DIR)/asm/code/lyt/drawInfo.cpp.o \
$(BUILD_DIR)/asm/code/lyt/group.cpp.o \
$(BUILD_DIR)/asm/code/lyt/layout.cpp.o \
$(BUILD_DIR)/asm/code/lyt/material.cpp.o \
$(BUILD_DIR)/asm/code/lyt/pane.cpp.o \
$(BUILD_DIR)/asm/code/lyt/picture.cpp.o \
$(BUILD_DIR)/asm/code/lyt/resourceAccessor.cpp.o \
$(BUILD_DIR)/asm/code/lyt/textBox.cpp.o \
$(BUILD_DIR)/asm/code/lyt/window.cpp.o \
$(BUILD_DIR)/asm/code/math/arithmetic.cpp.o \
$(BUILD_DIR)/asm/code/math/equation.cpp.o \
$(BUILD_DIR)/asm/code/math/triangular.cpp.o \
$(BUILD_DIR)/asm/code/snd/AnimSound.cpp.o \
$(BUILD_DIR)/asm/code/snd/AxManager.cpp.o \
$(BUILD_DIR)/asm/code/snd/AxVoice.cpp.o \
$(BUILD_DIR)/asm/code/snd/Bank.cpp.o \
$(BUILD_DIR)/asm/code/snd/BankFile.cpp.o \
$(BUILD_DIR)/asm/code/snd/BasicSound.cpp.o \
$(BUILD_DIR)/asm/code/snd/Channel.cpp.o \
$(BUILD_DIR)/asm/code/snd/DisposeCallbackManager.cpp.o \
$(BUILD_DIR)/asm/code/snd/DvdSoundArchive.cpp.o \
$(BUILD_DIR)/asm/code/snd/EnvGenerator.cpp.o \
$(BUILD_DIR)/asm/code/snd/ExternalHeap.cpp.o \
$(BUILD_DIR)/asm/code/snd/ExternalSoundPlayer.cpp.o \
$(BUILD_DIR)/asm/code/snd/FrameHeap.cpp.o \
$(BUILD_DIR)/asm/code/snd/InstancePool.cpp.o \
$(BUILD_DIR)/asm/code/snd/Lfo.cpp.o \
$(BUILD_DIR)/asm/code/snd/MemorySoundArchive.cpp.o \
$(BUILD_DIR)/asm/code/snd/MidiSeqPlayer.cpp.o \
$(BUILD_DIR)/asm/code/snd/MidiSeqTrack.cpp.o \
$(BUILD_DIR)/asm/code/snd/MidiSeqTrackAllocator.cpp.o \
$(BUILD_DIR)/asm/code/snd/MmlParser.cpp.o \
$(BUILD_DIR)/asm/code/snd/MmlSeqTrack.cpp.o \
$(BUILD_DIR)/asm/code/snd/MmlSeqTrackAllocator.cpp.o \
$(BUILD_DIR)/asm/code/snd/PlayerHeap.cpp.o \
$(BUILD_DIR)/asm/code/snd/RemoteSpeaker.cpp.o \
$(BUILD_DIR)/asm/code/snd/RemoteSpeakerManager.cpp.o \
$(BUILD_DIR)/asm/code/snd/SeqFile.cpp.o \
$(BUILD_DIR)/asm/code/snd/SeqPlayer.cpp.o \
$(BUILD_DIR)/asm/code/snd/SeqSound.cpp.o \
$(BUILD_DIR)/asm/code/snd/SeqSoundHandle.cpp.o \
$(BUILD_DIR)/asm/code/snd/SeqTrack.cpp.o \
$(BUILD_DIR)/asm/code/snd/Sound3DActor.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundArchive.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundArchiveFile.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundArchiveLoader.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundArchivePlayer.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundHandle.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundHeap.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundPlayer.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundStartable.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundSystem.cpp.o \
$(BUILD_DIR)/asm/code/snd/SoundThread.cpp.o \
$(BUILD_DIR)/asm/code/snd/StrmChannel.cpp.o \
$(BUILD_DIR)/asm/code/snd/StrmFile.cpp.o \
$(BUILD_DIR)/asm/code/snd/StrmPlayer.cpp.o \
$(BUILD_DIR)/asm/code/snd/StrmSound.cpp.o \
$(BUILD_DIR)/asm/code/snd/StrmSoundHandle.cpp.o \
$(BUILD_DIR)/asm/code/snd/TaskManager.cpp.o \
$(BUILD_DIR)/asm/code/snd/TaskThread.cpp.o \
$(BUILD_DIR)/asm/code/snd/Util.cpp.o \
$(BUILD_DIR)/asm/code/snd/WaveFile.cpp.o \
$(BUILD_DIR)/asm/code/snd/WavePlayer.cpp.o \
$(BUILD_DIR)/asm/code/snd/WaveSound.cpp.o \
$(BUILD_DIR)/asm/code/snd/WaveSoundHandle.cpp.o \
$(BUILD_DIR)/asm/code/snd/WsdFile.cpp.o \
$(BUILD_DIR)/asm/code/snd/WsdPlayer.cpp.o \
$(BUILD_DIR)/asm/code/snd/WsdTrack.cpp.o \
$(BUILD_DIR)/asm/code/ut/ArchiveFont.cpp.o \
$(BUILD_DIR)/asm/code/ut/binaryFileFormat.cpp.o \
$(BUILD_DIR)/asm/code/ut/CharStrmReader.cpp.o \
$(BUILD_DIR)/asm/code/ut/CharWriter.cpp.o \
$(BUILD_DIR)/asm/code/ut/DvdFileStream.cpp.o \
$(BUILD_DIR)/asm/code/ut/DvdLockedFileStream.cpp.o \
$(BUILD_DIR)/asm/code/ut/FileStream.cpp.o \
$(BUILD_DIR)/asm/code/ut/Font.cpp.o \
$(BUILD_DIR)/asm/code/ut/IOStream.cpp.o \
$(BUILD_DIR)/asm/code/ut/LinkList.cpp.o \
$(BUILD_DIR)/asm/code/ut/list.cpp.o \
$(BUILD_DIR)/asm/code/ut/ResFont.cpp.o \
$(BUILD_DIR)/asm/code/ut/ResFontBase.cpp.o \
$(BUILD_DIR)/asm/code/ut/TagProcessorBase.cpp.o \
$(BUILD_DIR)/asm/code/ut/TextWriterBase.cpp.o \
$(BUILD_DIR)/asm/code/ipcMain.c.o \
$(BUILD_DIR)/asm/code/ipcclt.c.o \
$(BUILD_DIR)/asm/code/memory.c.o \
$(BUILD_DIR)/asm/code/ipcProfile.c.o \
$(BUILD_DIR)/asm/code/KPAD.c.o \
$(BUILD_DIR)/asm/code/mem/heapCommon.c.o \
$(BUILD_DIR)/asm/code/mem/expHeap.c.o \
$(BUILD_DIR)/asm/code/mem/frameHeap.c.o \
$(BUILD_DIR)/asm/code/mem/unitHeap.c.o \
$(BUILD_DIR)/asm/code/mem/allocator.c.o \
$(BUILD_DIR)/asm/code/mem/list.c.o \
$(BUILD_DIR)/asm/code/mix.c.o \
$(BUILD_DIR)/asm/code/remote.c.o \
$(BUILD_DIR)/asm/code/mtx.c.o \
$(BUILD_DIR)/asm/code/mtxvec.c.o \
$(BUILD_DIR)/asm/code/mtx44.c.o \
$(BUILD_DIR)/asm/code/vec.c.o \
$(BUILD_DIR)/asm/code/nand.c.o \
$(BUILD_DIR)/asm/code/NANDOpenClose.c.o \
$(BUILD_DIR)/asm/code/NANDCore.c.o \
$(BUILD_DIR)/asm/code/NANDCheck.c.o \
$(BUILD_DIR)/asm/code/OS.c.o \
$(BUILD_DIR)/asm/code/OSAlarm.c.o \
$(BUILD_DIR)/asm/code/OSAlloc.c.o \
$(BUILD_DIR)/asm/code/OSArena.c.o \
$(BUILD_DIR)/asm/code/OSAudioSystem.c.o \
$(BUILD_DIR)/asm/code/OSCache.c.o \
$(BUILD_DIR)/asm/code/OSContext.c.o \
$(BUILD_DIR)/asm/code/OSError.c.o \
$(BUILD_DIR)/asm/code/OSExec.c.o \
$(BUILD_DIR)/asm/code/OSFatal.c.o \
$(BUILD_DIR)/asm/code/OSFont.c.o \
$(BUILD_DIR)/asm/code/OSInterrupt.c.o \
$(BUILD_DIR)/asm/code/OSLink.c.o \
$(BUILD_DIR)/asm/code/OSMessage.c.o \
$(BUILD_DIR)/asm/code/OSMemory.c.o \
$(BUILD_DIR)/asm/code/OSMutex.c.o \
$(BUILD_DIR)/asm/code/OSReboot.c.o \
$(BUILD_DIR)/asm/code/OSReset.c.o \
$(BUILD_DIR)/asm/code/OSRtc.c.o \
$(BUILD_DIR)/asm/code/OSSemaphore.c.o \
$(BUILD_DIR)/asm/code/OSSync.c.o \
$(BUILD_DIR)/asm/code/OSThread.c.o \
$(BUILD_DIR)/asm/code/OSTime.c.o \
$(BUILD_DIR)/asm/code/OSUtf.c.o \
$(BUILD_DIR)/asm/code/OSIpc.c.o \
$(BUILD_DIR)/asm/code/OSStateTM.c.o \
$(BUILD_DIR)/asm/code/OSPlayRecord.c.o \
$(BUILD_DIR)/asm/code/OSStateFlags.c.o \
$(BUILD_DIR)/asm/code/OSNet.c.o \
$(BUILD_DIR)/asm/code/OSNandbootInfo.c.o \
$(BUILD_DIR)/asm/code/Pad.c.o \
$(BUILD_DIR)/asm/code/scsystem.c.o \
$(BUILD_DIR)/asm/code/scapi.c.o \
$(BUILD_DIR)/asm/code/scapi/prdinfo.c.o \
$(BUILD_DIR)/asm/code/SIBios.c.o \
$(BUILD_DIR)/asm/code/SISamplingRate.c.o \
$(BUILD_DIR)/asm/code/TPL.c.o \
$(BUILD_DIR)/asm/code/usb.c.o \
$(BUILD_DIR)/asm/code/vi.c.o \
$(BUILD_DIR)/asm/code/i2c.c.o \
$(BUILD_DIR)/asm/code/vi3in1.c.o \
$(BUILD_DIR)/asm/code/wenc.c.o \
$(BUILD_DIR)/asm/code/WPAD.c.o \
$(BUILD_DIR)/asm/code/WPADHIDParser.c.o \
$(BUILD_DIR)/asm/code/WPADEncrypt.c.o \
$(BUILD_DIR)/asm/code/debug/msg.c.o \
$(BUILD_DIR)/asm/code/WUD.c.o \
$(BUILD_DIR)/asm/code/WUDHidHost.c.o \
$(BUILD_DIR)/asm/code/DebuggerDriver.c.o \
$(BUILD_DIR)/asm/code/exi2.c.o \
$(BUILD_DIR)/asm/code/ansi/files.c.o \
$(BUILD_DIR)/asm/code/ansi/fp.c.o \
$(BUILD_DIR)/asm/code/arith.c.o \
$(BUILD_DIR)/asm/code/bsearch.c.o \
$(BUILD_DIR)/asm/code/buffer/io.c.o \
$(BUILD_DIR)/asm/code/ctype.c.o \
$(BUILD_DIR)/asm/code/direct/io.c.o \
$(BUILD_DIR)/asm/code/file/io.c.o \
$(BUILD_DIR)/asm/code/FILE/POS.C.o \
$(BUILD_DIR)/asm/code/mbstring.c.o \
$(BUILD_DIR)/asm/code/mem.c.o \
$(BUILD_DIR)/asm/code/mem/funcs.c.o \
$(BUILD_DIR)/asm/code/math/api.c.o \
$(BUILD_DIR)/asm/code/misc/io.c.o \
$(BUILD_DIR)/asm/code/printf.c.o \
$(BUILD_DIR)/asm/code/qsort.c.o \
$(BUILD_DIR)/asm/code/rand.c.o \
$(BUILD_DIR)/asm/code/scanf.c.o \
$(BUILD_DIR)/asm/code/string.c.o \
$(BUILD_DIR)/asm/code/strtold.c.o \
$(BUILD_DIR)/asm/code/strtoul.c.o \
$(BUILD_DIR)/asm/code/wstring.c.o \
$(BUILD_DIR)/asm/code/wchar/io.c.o \
$(BUILD_DIR)/asm/code/uart/console/io/gcn.c.o \
$(BUILD_DIR)/asm/code/math/sun.c.o \
$(BUILD_DIR)/asm/code/math/double.c.o \
$(BUILD_DIR)/asm/code/extras.c.o \
$(BUILD_DIR)/asm/code/e/acos.c.o \
$(BUILD_DIR)/asm/code/e/asin.c.o \
$(BUILD_DIR)/asm/code/e/atan2.c.o \
$(BUILD_DIR)/asm/code/e/exp.c.o \
$(BUILD_DIR)/asm/code/e/fmod.c.o \
$(BUILD_DIR)/asm/code/e/log.c.o \
$(BUILD_DIR)/asm/code/e/log10.c.o \
$(BUILD_DIR)/asm/code/e/pow.c.o \
$(BUILD_DIR)/asm/code/e/rem/pio2.c.o \
$(BUILD_DIR)/asm/code/k/cos.c.o \
$(BUILD_DIR)/asm/code/k/rem/pio2.c.o \
$(BUILD_DIR)/asm/code/k/sin.c.o \
$(BUILD_DIR)/asm/code/k/tan.c.o \
$(BUILD_DIR)/asm/code/s/atan.c.o \
$(BUILD_DIR)/asm/code/s/ceil.c.o \
$(BUILD_DIR)/asm/code/s/copysign.c.o \
$(BUILD_DIR)/asm/code/s/cos.c.o \
$(BUILD_DIR)/asm/code/s/floor.c.o \
$(BUILD_DIR)/asm/code/s/frexp.c.o \
$(BUILD_DIR)/asm/code/s/ldexp.c.o \
$(BUILD_DIR)/asm/code/s/modf.c.o \
$(BUILD_DIR)/asm/code/s/sin.c.o \
$(BUILD_DIR)/asm/code/s/tan.c.o \
$(BUILD_DIR)/asm/code/w/acos.c.o \
$(BUILD_DIR)/asm/code/w/asin.c.o \
$(BUILD_DIR)/asm/code/w/atan2.c.o \
$(BUILD_DIR)/asm/code/w/exp.c.o \
$(BUILD_DIR)/asm/code/w/fmod.c.o \
$(BUILD_DIR)/asm/code/w/log.c.o \
$(BUILD_DIR)/asm/code/w/log10.c.o \
$(BUILD_DIR)/asm/code/w/pow.c.o \
$(BUILD_DIR)/asm/code/e/sqrt.c.o \
$(BUILD_DIR)/asm/code/math/ppc.c.o \
$(BUILD_DIR)/asm/code/w/sqrt.c.o \
$(BUILD_DIR)/asm/code/__va_arg.c.o \
$(BUILD_DIR)/asm/code/global/destructor/chain.c.o \
$(BUILD_DIR)/asm/code/NMWException.cp.o \
$(BUILD_DIR)/asm/code/ptmf.c.o \
$(BUILD_DIR)/asm/code/runtime.c.o \
$(BUILD_DIR)/asm/code/__init_cpp_exceptions.cpp.o \
$(BUILD_DIR)/asm/code/Gecko/ExceptionPPC.cp.o \
$(BUILD_DIR)/asm/code/mainloop.c.o \
$(BUILD_DIR)/asm/code/nubevent.c.o \
$(BUILD_DIR)/asm/code/nubinit.c.o \
$(BUILD_DIR)/asm/code/msg.c.o \
$(BUILD_DIR)/asm/code/msgbuf.c.o \
$(BUILD_DIR)/asm/code/serpoll.c.o \
$(BUILD_DIR)/asm/code/usr/put.c.o \
$(BUILD_DIR)/asm/code/dispatch.c.o \
$(BUILD_DIR)/asm/code/msghndlr.c.o \
$(BUILD_DIR)/asm/code/support.c.o \
$(BUILD_DIR)/asm/code/mutex/TRK.c.o \
$(BUILD_DIR)/asm/code/notify.c.o \
$(BUILD_DIR)/asm/code/flush/cache.c.o \
$(BUILD_DIR)/asm/code/string/TRK.c.o \
$(BUILD_DIR)/asm/code/targimpl.c.o \
$(BUILD_DIR)/asm/code/targsupp.s.o \
$(BUILD_DIR)/asm/code/mpc/7xx/603e.c.o \
$(BUILD_DIR)/asm/code/mslsupp.c.o \
$(BUILD_DIR)/asm/code/main/TRK.c.o \
$(BUILD_DIR)/asm/code/dolphin/trk/glue.c.o \
$(BUILD_DIR)/asm/code/targcont.c.o \
$(BUILD_DIR)/asm/code/target/options.c.o \
$(BUILD_DIR)/asm/code/UDP/Stubs.c.o \
$(BUILD_DIR)/asm/code/main.c.o \
$(BUILD_DIR)/asm/code/CircleBuffer.c.o \
$(BUILD_DIR)/asm/code/MWCriticalSection/gc.cpp.o \
$(BUILD_DIR)/asm/code/GDBase.c.o \
$(BUILD_DIR)/asm/code/THPDec.c.o \
$(BUILD_DIR)/asm/ctors.o \
$(BUILD_DIR)/asm/dtors.o \
$(BUILD_DIR)/asm/code/bta/dm/cfg.c.o \
$(BUILD_DIR)/asm/code/bta/hh/cfg.c.o \
$(BUILD_DIR)/asm/code/locale.c.o \
$(BUILD_DIR)/asm/code/wctype.c.o \
$(BUILD_DIR)/asm/code/AXComp.c.o \
$(BUILD_DIR)/asm/code/DSPCode.c.o \
$(BUILD_DIR)/asm/code/WPADMem.c.o \
$(BUILD_DIR)/asm/code/bta/sys/cfg.c.o \
$(BUILD_DIR)/asm/code/float.cpp.o \
$(BUILD_DIR)/asm/code/bomb.cpp.o \
$(BUILD_DIR)/asm/code/string.cpp.o \
$(BUILD_DIR)/asm/code/AptGlobalExtensionObject.cpp.o \
$(BUILD_DIR)/asm/code/errno.c.o \
$(BUILD_DIR)/asm/code/abort/exit/ppc/eabi.c.o